VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	src/compositeTypes_pkg.vhd \
	src/compositeTypes.vhd \
	tb/compositeTypes_tb.vhd


TB=compositeTypes_tb
WAVE_FILE=wave.do

include ../../../util/simple_flow.mk
