VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	src/test_pkg.vhd \
	src/helper_pkg.vhd \
	src/test.vhd \
	src/and.vhd \
	src/and_generic.vhd \
	tb/test_tb.vhd 


TB=test_tb
WAVE_FILE=wave.do

include ../../../util/simple_flow.mk
