VHDL_FILES =\
	../../../lib/math/src/math_pkg.vhd\
	src/test_pkg.vhd \
	src/and_gate.vhd \
	src/xor_gate.vhd \
	src/ha_gate.vhd \
	src/fa_gate.vhd \
	src/test.vhd \
	tb/test_tb.vhd


TB=test_tb
WAVE_FILE=wave.do

include ../../../util/simple_flow.mk
